# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           /:categories/:title.html
relative_permalinks: true

# Setup
title:               Meaningful Ink
tagline:             '&nbsp  — &nbsp Thoughts on the inside & outside world'
description:         'Thoughts, essays, and short fiction imperfectly translated to the written word by a young man looking for meaning.'
url:                 http://meaningful.ink
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Meaningful Ink
  url:               http://meaningful.ink
  email:             e.grayham@protonmail.ch

# Custom vars
version:             1.0.0
